### ISSUE TITLE
KMP in C++

### ISSUE THREAD

**Issue by madhabi8240** [madhabi8240/Algorithm-with-cpp#12]

**Comment by Renu-code** [comment]
I can implement the kmp algorithm in c++.. can you please assign this issue to me??

**Comment by madhabi8240** [comment]
yes

**Comment by Renu-code** [comment]
@madhabi8240 Hello, I have added the kmp algorithm ..please review it #17

**Comment by Renu-code** [comment]
sorry for the inconvenience @madhabi8240 ...i have again added the kmp algo..please check it #22
